// src-cli/index.ts
import { Command } from "commander";
import chalk7 from "chalk";

// src-cli/commands/init.ts
import { select, input } from "@inquirer/prompts";
import chalk from "chalk";
import ora from "ora";
import fs from "fs-extra";
import path from "path";
import execa from "execa";
var WEBIU_REPO = "https://github.com/TarunyaProgrammer/Webiu.git";
var WEBIU_BRANCH = "webiu-npm-pack";
async function initCommand(options) {
  console.log(`
${chalk.bold.cyan("====================================================")}`);
  console.log(`${chalk.bold.yellow("   Welcome to Webiu CLI Project Setup Wizard! :D   ")}`);
  console.log(`${chalk.bold.cyan("====================================================")}
`);
  const projectName = options.name || await input({
    message: "What is your project directory name?",
    default: "my-webiu-portal"
  });
  const orgType = await select({
    message: "Select your Organization Type:",
    choices: [
      { name: "Open Source Community (e.g., C2SI, SugarLabs)", value: "opensource" },
      { name: "Non-Profit Organization", value: "nonprofit" },
      { name: "Startup / Personal Project", value: "startup" },
      { name: "Custom / Blank Setup", value: "custom" }
    ]
  });
  const orgName = await input({
    message: "What is your Organization Name?",
    default: "My Community Org"
  });
  const githubOrg = await input({
    message: "What is your GitHub Organization / User name?",
    default: "c2siorg"
  });
  const dbStrategy = await select({
    message: "Select Database Setup Strategy:",
    choices: [
      { name: "PostgreSQL Container  (Automatic local Docker DB - Recommended)", value: "docker-postgres" },
      { name: "Remote PostgreSQL     (Provide your own connection string URL)", value: "remote-postgres" },
      { name: "SQLite Light Mode     (Zero-config, no Docker needed)", value: "sqlite" }
    ]
  });
  let databaseUrl = "postgresql://postgres:postgres@localhost:5432/webiu_db";
  if (dbStrategy === "remote-postgres") {
    databaseUrl = await input({
      message: "Enter your PostgreSQL Connection String URL:",
      default: databaseUrl
    });
  }
  const themeAccent = await select({
    message: "Select Primary UI Theme Accent:",
    choices: [
      { name: "Ocean Blue     (#0052CC)", value: "#0052CC" },
      { name: "Emerald Green  (#10B981)", value: "#10B981" },
      { name: "Deep Purple    (#7C3AED)", value: "#7C3AED" },
      { name: "Sunset Crimson (#EF4444)", value: "#EF4444" }
    ]
  });
  const deployTarget = await select({
    message: "Select Target Deployment Platform:",
    choices: [
      { name: "Render              (Fullstack App + Postgres DB - Guided config)", value: "render" },
      { name: "Railway             (Instant container deployment)", value: "railway" },
      { name: "Vercel + Render     (Static Angular UI + NestJS API on Render)", value: "vercel-render" },
      { name: "Self-Hosted Docker  (Generates docker-compose.prod.yml)", value: "docker" }
    ]
  });
  const projectDir = path.resolve(process.cwd(), projectName);
  if (await fs.pathExists(projectDir)) {
    const existing = await fs.readdir(projectDir);
    if (existing.length > 0) {
      console.log(chalk.red(`
Directory "${projectName}" already exists and is not empty. :(`));
      console.log(chalk.yellow("Please choose an empty directory or delete the existing one.\n"));
      process.exit(1);
    }
  }
  await fs.ensureDir(projectDir);
  const spinner = ora({
    text: `Cloning Webiu source code into "${projectName}"... (this may take a moment)`,
    color: "cyan"
  }).start();
  try {
    await execa("git", [
      "clone",
      "--branch",
      WEBIU_BRANCH,
      "--single-branch",
      "--depth=1",
      WEBIU_REPO,
      projectDir
    ], { stdio: "pipe" });
    spinner.text = "Injecting your organization configuration...";
    const jwtSecret = Math.random().toString(36).substring(2, 10) + Math.random().toString(36).substring(2, 10);
    const envContent = [
      "# Generated by Webiu CLI - Do not commit this file to version control",
      `PORT=3000`,
      `NODE_ENV=development`,
      `ORG_NAME="${orgName}"`,
      `GITHUB_ORG="${githubOrg}"`,
      `ORG_TYPE="${orgType}"`,
      `THEME_ACCENT="${themeAccent}"`,
      `DEPLOY_TARGET="${deployTarget}"`,
      `DATABASE_URL="${databaseUrl}"`,
      `JWT_SECRET="${jwtSecret}"`
    ].join("\n");
    await fs.writeFile(path.join(projectDir, ".env"), envContent);
    const serverEnvPath = path.join(projectDir, "webiu-server", ".env");
    if (await fs.pathExists(path.dirname(serverEnvPath))) {
      const serverEnvContent = [
        "# Generated by Webiu CLI",
        `PORT=3000`,
        `NODE_ENV=development`,
        `DATABASE_URL="${databaseUrl}"`,
        `JWT_SECRET="${jwtSecret}"`,
        `GITHUB_ORG="${githubOrg}"`
      ].join("\n");
      await fs.writeFile(serverEnvPath, serverEnvContent);
    }
    const uiConfigPath = path.join(projectDir, "webiu-ui", "src", "assets", "config.json");
    if (await fs.pathExists(path.dirname(uiConfigPath))) {
      await fs.writeJson(uiConfigPath, {
        orgName,
        githubOrg,
        orgType,
        themeAccent,
        apiUrl: "http://localhost:3000",
        graphqlUrl: "http://localhost:3000/graphql"
      }, { spaces: 2 });
    }
    spinner.succeed(chalk.green(`Project "${chalk.bold(projectName)}" scaffolded successfully! XD`));
    console.log(`
${chalk.bold.yellow("===================================================================")}
${chalk.bold.green("   Your Webiu portal is ready! Here is what to do next:            ")}
${chalk.bold.yellow("===================================================================")}

  ${chalk.bold("1. Enter your project directory:")}
     ${chalk.cyan(`cd ${projectName}`)}

  ${chalk.bold("2. Install all dependencies:")}
     ${chalk.cyan("cd webiu-server && npm install && cd ../webiu-ui && npm install && cd ..")}

  ${chalk.bold("3. Start development servers:")}
     ${chalk.cyan("npx webiu dev")}
     ${chalk.gray("   Frontend UI  ->  http://localhost:4200")}
     ${chalk.gray("   Backend API  ->  http://localhost:3000")}

  ${chalk.bold("4. Generate deployment files:")}
     ${chalk.cyan("npx webiu deploy")}

${chalk.bold.yellow("-------------------------------------------------------------------")}
${chalk.bold('  TIP: To use "webiu" directly without "npx" every time:')}
  ${chalk.cyan("npm install -g create-webiu")}
  ${chalk.gray("  Then you can simply type: webiu init, webiu dev, webiu help, etc.")}
${chalk.bold.yellow("===================================================================")}
`);
  } catch (err) {
    spinner.fail(chalk.red("Scaffolding failed!"));
    if (err.message && err.message.includes("git")) {
      console.error(chalk.red("\nGit is required to scaffold a Webiu project."));
      console.error(chalk.yellow("Please install git from https://git-scm.com and try again.\n"));
    } else {
      console.error(err);
    }
    const existing = await fs.readdir(projectDir).catch(() => []);
    if (existing.length === 0) {
      await fs.remove(projectDir);
    }
    process.exit(1);
  }
}

// src-cli/commands/dev.ts
import concurrently from "concurrently";
import chalk2 from "chalk";
import path2 from "path";
import fs2 from "fs-extra";
async function devCommand() {
  console.log(`
${chalk2.bold.cyan("Starting Webiu Development Server (Frontend + Backend)... :D")}
`);
  const serverDir = path2.join(process.cwd(), "webiu-server");
  const uiDir = path2.join(process.cwd(), "webiu-ui");
  if (!await fs2.pathExists(serverDir) || !await fs2.pathExists(uiDir)) {
    console.error(chalk2.red("\nError: webiu-server or webiu-ui directories not found in current directory! :("));
    console.error(chalk2.yellow("Make sure you have run `npx webiu init` first and are inside your project directory."));
    console.error(chalk2.yellow(`Expected: ${chalk2.cyan(serverDir)}`));
    console.error(chalk2.yellow(`Expected: ${chalk2.cyan(uiDir)}
`));
    process.exit(1);
  }
  const serverModules = path2.join(serverDir, "node_modules");
  const uiModules = path2.join(uiDir, "node_modules");
  if (!await fs2.pathExists(serverModules) || !await fs2.pathExists(uiModules)) {
    console.error(chalk2.red("\nError: node_modules not found in webiu-server or webiu-ui! :("));
    console.error(chalk2.yellow("Please run the following commands first:"));
    console.error(chalk2.cyan("  cd webiu-server && npm install && cd .."));
    console.error(chalk2.cyan("  cd webiu-ui && npm install && cd ..\n"));
    process.exit(1);
  }
  console.log(chalk2.gray("  Backend API : http://localhost:3000"));
  console.log(chalk2.gray("  Frontend UI : http://localhost:4200"));
  console.log(chalk2.gray("  Press Ctrl+C to stop all servers\n"));
  try {
    const { result } = concurrently(
      [
        {
          command: "npm run start:dev",
          name: "backend",
          cwd: serverDir,
          prefixColor: "blue"
        },
        {
          command: "npm start",
          name: "frontend",
          cwd: uiDir,
          prefixColor: "green"
        }
      ],
      {
        prefix: "name",
        killOthersOn: ["failure"],
        restartTries: 0
      }
    );
    await result;
  } catch (err) {
    console.error(chalk2.red("\nDevelopment servers stopped unexpectedly:"), err);
  }
}
async function buildCommand() {
  console.log(`
${chalk2.bold.cyan("Building production bundles for Webiu... XD")}
`);
  const serverDir = path2.join(process.cwd(), "webiu-server");
  const uiDir = path2.join(process.cwd(), "webiu-ui");
  if (!await fs2.pathExists(serverDir) || !await fs2.pathExists(uiDir)) {
    console.error(chalk2.red("Error: webiu-server or webiu-ui directories not found. Run `npx webiu init` first."));
    process.exit(1);
  }
  const execa3 = (await import("execa")).default;
  console.log(chalk2.cyan("Building NestJS backend..."));
  await execa3("npm", ["run", "build"], { cwd: serverDir, stdio: "inherit" });
  console.log(chalk2.cyan("\nBuilding Angular frontend..."));
  await execa3("npm", ["run", "build"], { cwd: uiDir, stdio: "inherit" });
  console.log(chalk2.green("\nBuild complete! XD"));
}

// src-cli/commands/config.ts
import { select as select2 } from "@inquirer/prompts";
import chalk3 from "chalk";
import ora2 from "ora";
async function configCommand() {
  console.log(`
${chalk3.bold.cyan("====================================================")}`);
  console.log(`${chalk3.bold.yellow("        Webiu Interactive Configuration Manager      ")}`);
  console.log(`${chalk3.bold.cyan("====================================================")}
`);
  const setting = await select2({
    message: "What would you like to re-configure?",
    choices: [
      { name: "Organization Name & Details", value: "org" },
      { name: "Branding Theme & Accent Colors", value: "theme" },
      { name: "Database Connection Credentials", value: "db" },
      { name: "JWT & OAuth Authentication Keys", value: "auth" }
    ]
  });
  const spinner = ora2("Updating configuration parameters...").start();
  spinner.succeed(chalk3.green(`Successfully updated ${setting} configuration! XD`));
}

// src-cli/commands/deploy.ts
import { select as select3 } from "@inquirer/prompts";
import chalk4 from "chalk";
import ora3 from "ora";
import fs3 from "fs-extra";
import path3 from "path";
async function deployCommand() {
  console.log(`
${chalk4.bold.cyan("====================================================")}`);
  console.log(`${chalk4.bold.yellow("      Webiu Interactive Deployment Generator       ")}`);
  console.log(`${chalk4.bold.cyan("====================================================")}
`);
  const platform = await select3({
    message: "Select target cloud platform for deployment:",
    choices: [
      {
        name: "Render (Fullstack Blueprint - Server + UI + Postgres DB)",
        value: "render",
        description: "Generates render.yaml for one-click Infrastructure-as-Code deployment"
      },
      {
        name: "Railway (Containerized Service Deployment)",
        value: "railway",
        description: "Generates railway.json container configuration"
      },
      {
        name: "Vercel + Render (Static Angular UI on Vercel + NestJS API on Render)",
        value: "vercel-render",
        description: "Configures Vercel static build and Render backend environment"
      },
      {
        name: "Self-Hosted Production Docker (Docker Compose)",
        value: "docker",
        description: "Generates production docker-compose.prod.yml with Nginx reverse proxy"
      }
    ]
  });
  const spinner = ora3(`Generating deployment configuration files for ${platform}...`).start();
  try {
    if (platform === "render") {
      const renderYaml = `
services:
  - type: web
    name: webiu-server
    env: node
    buildCommand: cd webiu-server && npm install && npm run build
    startCommand: cd webiu-server && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: webiu-ui
    env: static
    buildCommand: cd webiu-ui && npm install && npm run build
    staticPublishPath: ./webiu-ui/dist/webiu-ui/browser
`.trim();
      await fs3.writeFile(path3.join(process.cwd(), "render.yaml"), renderYaml);
      spinner.succeed(chalk4.green("Generated render.yaml successfully! XD"));
      console.log(`
${chalk4.bold.yellow("Next Steps for Render:")}`);
      console.log("  1. Commit and push your changes to GitHub.");
      console.log('  2. Go to https://dashboard.render.com and choose "New Blueprint Group".');
      console.log("  3. Select your GitHub repo to deploy automatically!\n");
    } else if (platform === "docker") {
      const dockerProd = `
version: '3.8'
services:
  webiu-server:
    build:
      context: ./webiu-server
    ports:
      - "3000:3000"
    restart: always

  webiu-ui:
    build:
      context: ./webiu-ui
    ports:
      - "80:80"
    restart: always
`.trim();
      await fs3.writeFile(path3.join(process.cwd(), "docker-compose.prod.yml"), dockerProd);
      spinner.succeed(chalk4.green("Generated docker-compose.prod.yml successfully! :D"));
      console.log(`
${chalk4.bold.yellow("Next Steps for Docker:")}`);
      console.log(`  1. Run ${chalk4.cyan("docker compose -f docker-compose.prod.yml up -d")}`);
      console.log("  2. Access your portal at http://localhost\n");
    } else {
      spinner.succeed(chalk4.green(`Prepared deployment instructions for ${platform}!`));
    }
  } catch (err) {
    spinner.fail(chalk4.red("Failed to generate deployment templates."));
    console.error(err);
  }
}

// src-cli/commands/help.ts
import chalk5 from "chalk";
async function helpCommand() {
  console.log(`
${chalk5.bold.cyan("====================================================================")}
${chalk5.bold.yellow("                        WEBIU CLI TOOL - HELP MANUAL                ")}
${chalk5.bold.cyan("====================================================================")}

${chalk5.bold("Usage:")} webiu [command] [options]

${chalk5.bold.green("Commands:")}
  ${chalk5.bold.cyan("init")}          Interactively initialize a new Webiu portal project
  ${chalk5.bold.cyan("dev")}           Start local development server (Frontend + Backend concurrently)
  ${chalk5.bold.cyan("build")}         Build production assets for both webiu-ui and webiu-server
  ${chalk5.bold.cyan("config")}        Re-configure Organization metadata, branding, or environment variables
  ${chalk5.bold.cyan("deploy")}        Launch interactive deployment generator for Render, Railway, Vercel, or Docker
  ${chalk5.bold.cyan("docker:up")}     Spin up containerized development environment using Docker Compose
  ${chalk5.bold.cyan("docker:down")}   Stop and remove running local Docker containers
  ${chalk5.bold.cyan("help")}          Display detailed command usage and architectural instructions

${chalk5.bold.green("Options:")}
  ${chalk5.bold.cyan("-v, --version")} Output the current version of webiu
  ${chalk5.bold.cyan("-h, --help")}    Display help information for command

${chalk5.bold.magenta("Examples:")}
  $ ${chalk5.cyan("npx webiu init")}
  $ ${chalk5.cyan("npx webiu dev")}
  $ ${chalk5.cyan("npx webiu deploy")}

${chalk5.gray("For detailed online documentation, visit:")} ${chalk5.underline.blue("https://github.com/c2siorg/Webiu")}
${chalk5.gray("Maintainers: C2SI Organization (Community Software Infrastructure)")} XD
`);
}

// src-cli/commands/docker.ts
import { execa as execa2 } from "execa";
import chalk6 from "chalk";
async function dockerUpCommand() {
  console.log(`
${chalk6.bold.cyan("Starting Docker containerized environment... :D")}
`);
  try {
    await execa2("docker", ["compose", "up", "-d"], { stdio: "inherit" });
    console.log(chalk6.green("\nDocker containers started successfully! XD"));
  } catch (err) {
    console.error(chalk6.red("Failed to start Docker containers:"), err);
  }
}
async function dockerDownCommand() {
  console.log(`
${chalk6.bold.cyan("Stopping Docker containerized environment...")}
`);
  try {
    await execa2("docker", ["compose", "down"], { stdio: "inherit" });
    console.log(chalk6.green("\nDocker containers stopped cleanly."));
  } catch (err) {
    console.error(chalk6.red("Failed to stop Docker containers:"), err);
  }
}

// src-cli/index.ts
var program = new Command();
program.name("webiu").description("CLI tool to generate, configure, and deploy Webiu community portals").version("1.0.5").addHelpCommand(false).helpOption("-h, --help", "Display command usage and instructions");
program.command("init").description("Interactively initialize a new Webiu portal project").option("-n, --name <name>", "Project name").action(initCommand);
program.command("dev").description("Start local development server (Frontend + Backend concurrently)").action(devCommand);
program.command("build").description("Build production assets for both webiu-ui and webiu-server").action(buildCommand);
program.command("config").description("Re-configure Organization metadata, branding, or environment variables").action(configCommand);
program.command("deploy").description("Launch interactive deployment generator for Render, Railway, Vercel, or Docker").action(deployCommand);
program.command("docker:up").description("Spin up containerized development environment using Docker Compose").action(dockerUpCommand);
program.command("docker:down").description("Stop and remove running local Docker containers").action(dockerDownCommand);
program.command("help").description("Display detailed command usage and architectural instructions").action(helpCommand);
program.on("command:*", (operands) => {
  console.error(chalk7.red(`
Command not found: "${operands[0]}". See available commands below: :(
`));
  helpCommand();
  process.exit(1);
});
program.parse(process.argv);
if (!process.argv.slice(2).length) {
  helpCommand();
}
