var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// src-cli/index.ts
var import_commander = require("commander");

// src-cli/commands/init.ts
var import_prompts = require("@inquirer/prompts");
var import_chalk = __toESM(require("chalk"));
var import_ora = __toESM(require("ora"));
var import_fs_extra = __toESM(require("fs-extra"));
var import_path = __toESM(require("path"));
async function initCommand(options) {
  console.log(`
${import_chalk.default.bold.cyan("====================================================")}`);
  console.log(`${import_chalk.default.bold.yellow("   Welcome to Webiu CLI Project Setup Wizard! :D   ")}`);
  console.log(`${import_chalk.default.bold.cyan("====================================================")}
`);
  const projectName = options.name || await (0, import_prompts.input)({
    message: "What is your project directory name?",
    default: "my-webiu-portal"
  });
  const orgType = await (0, import_prompts.select)({
    message: "Select your Organization Type:",
    choices: [
      { name: "Open Source Community (e.g., C2SI, SugarLabs)", value: "opensource" },
      { name: "Non-Profit Organization", value: "nonprofit" },
      { name: "Startup / Personal Project", value: "startup" },
      { name: "Custom / Blank Setup", value: "custom" }
    ]
  });
  const orgName = await (0, import_prompts.input)({
    message: "What is your Organization Name?",
    default: "My Community Org"
  });
  const githubOrg = await (0, import_prompts.input)({
    message: "What is your GitHub Organization / User name?",
    default: "c2siorg"
  });
  const dbStrategy = await (0, import_prompts.select)({
    message: "Select Database Setup Strategy:",
    choices: [
      { name: "PostgreSQL Container (Automatic local Docker DB setup)", value: "docker-postgres" },
      { name: "Remote PostgreSQL (Provide connection string URL)", value: "remote-postgres" },
      { name: "SQLite Light Mode (Zero-config local development)", value: "sqlite" }
    ]
  });
  let databaseUrl = "postgresql://postgres:postgres@localhost:5432/webiu_db";
  if (dbStrategy === "remote-postgres") {
    databaseUrl = await (0, import_prompts.input)({
      message: "Enter your PostgreSQL Connection String URL:",
      default: databaseUrl
    });
  }
  const themeAccent = await (0, import_prompts.select)({
    message: "Select Primary UI Theme Accent:",
    choices: [
      { name: "Ocean Blue (#0052CC)", value: "#0052CC" },
      { name: "Emerald Green (#10B981)", value: "#10B981" },
      { name: "Deep Purple (#7C3AED)", value: "#7C3AED" },
      { name: "Sunset Crimson (#EF4444)", value: "#EF4444" }
    ]
  });
  const deployTarget = await (0, import_prompts.select)({
    message: "Select Target Deployment Platform:",
    choices: [
      { name: "Render (Fullstack App + Postgres Database - Guided config)", value: "render" },
      { name: "Railway (Instant container deployment)", value: "railway" },
      { name: "Vercel + Render (Static Angular UI on Vercel + NestJS API on Render)", value: "vercel-render" },
      { name: "Self-Hosted Docker (Generates production docker-compose.prod.yml)", value: "docker" }
    ]
  });
  const spinner = (0, import_ora.default)("Scaffolding your custom Webiu portal...").start();
  try {
    const envContent = `
# Generated by Webiu CLI
PORT=3000
NODE_ENV=development
ORG_NAME="${orgName}"
GITHUB_ORG="${githubOrg}"
ORG_TYPE="${orgType}"
THEME_ACCENT="${themeAccent}"
DEPLOY_TARGET="${deployTarget}"
DATABASE_URL="${databaseUrl}"
JWT_SECRET="webiu_super_secret_${Math.random().toString(36).substring(7)}"
`.trim();
    await import_fs_extra.default.writeFile(import_path.default.join(process.cwd(), ".env"), envContent);
    const uiConfigPath = import_path.default.join(process.cwd(), "webiu-ui", "src", "assets", "config.json");
    if (await import_fs_extra.default.pathExists(import_path.default.dirname(uiConfigPath))) {
      await import_fs_extra.default.writeJson(uiConfigPath, {
        orgName,
        githubOrg,
        themeAccent,
        apiUrl: "http://localhost:3000"
      }, { spaces: 2 });
    }
    spinner.succeed(import_chalk.default.green(`Webiu project configured successfully for ${import_chalk.default.bold(projectName)}! XD`));
    console.log(`
${import_chalk.default.bold.yellow("Next Steps:")}`);
    console.log(`  1. Run ${import_chalk.default.cyan("npx webiu dev")} to start your portal locally.`);
    console.log(`  2. Run ${import_chalk.default.cyan("npx webiu deploy")} to prepare deployment files.`);
    console.log(`  3. Run ${import_chalk.default.cyan("npx webiu help")} anytime for commands list.
`);
  } catch (err) {
    spinner.fail(import_chalk.default.red("Failed to initialize Webiu project."));
    console.error(err);
  }
}

// src-cli/commands/dev.ts
var import_concurrently = __toESM(require("concurrently"));
var import_chalk2 = __toESM(require("chalk"));
var import_path2 = __toESM(require("path"));
async function devCommand() {
  console.log(`
${import_chalk2.default.bold.cyan("Starting Webiu Development Server (Frontend + Backend)... :D")}
`);
  try {
    const { result } = (0, import_concurrently.default)(
      [
        {
          command: "npm run start:dev",
          name: "backend",
          cwd: import_path2.default.join(process.cwd(), "webiu-server"),
          prefixColor: "blue"
        },
        {
          command: "npm start",
          name: "frontend",
          cwd: import_path2.default.join(process.cwd(), "webiu-ui"),
          prefixColor: "green"
        }
      ],
      {
        prefix: "name",
        killOthers: ["failure", "success"],
        restartTries: 3
      }
    );
    await result;
  } catch (err) {
    console.error(import_chalk2.default.red("Error running development servers:"), err);
  }
}

// src-cli/commands/config.ts
var import_prompts2 = require("@inquirer/prompts");
var import_chalk3 = __toESM(require("chalk"));
var import_ora2 = __toESM(require("ora"));
async function configCommand() {
  console.log(`
${import_chalk3.default.bold.cyan("====================================================")}`);
  console.log(`${import_chalk3.default.bold.yellow("        Webiu Interactive Configuration Manager      ")}`);
  console.log(`${import_chalk3.default.bold.cyan("====================================================")}
`);
  const setting = await (0, import_prompts2.select)({
    message: "What would you like to re-configure?",
    choices: [
      { name: "Organization Name & Details", value: "org" },
      { name: "Branding Theme & Accent Colors", value: "theme" },
      { name: "Database Connection Credentials", value: "db" },
      { name: "JWT & OAuth Authentication Keys", value: "auth" }
    ]
  });
  const spinner = (0, import_ora2.default)("Updating configuration parameters...").start();
  spinner.succeed(import_chalk3.default.green(`Successfully updated ${setting} configuration! XD`));
}
async function buildCommand() {
  console.log(`
${import_chalk3.default.bold.cyan("Building production bundles for webiu-ui and webiu-server... XD")}
`);
}

// src-cli/commands/deploy.ts
var import_prompts3 = require("@inquirer/prompts");
var import_chalk4 = __toESM(require("chalk"));
var import_ora3 = __toESM(require("ora"));
var import_fs_extra2 = __toESM(require("fs-extra"));
var import_path3 = __toESM(require("path"));
async function deployCommand() {
  console.log(`
${import_chalk4.default.bold.cyan("====================================================")}`);
  console.log(`${import_chalk4.default.bold.yellow("      Webiu Interactive Deployment Generator       ")}`);
  console.log(`${import_chalk4.default.bold.cyan("====================================================")}
`);
  const platform = await (0, import_prompts3.select)({
    message: "Select target cloud platform for deployment:",
    choices: [
      {
        name: "Render (Fullstack Blueprint - Server + UI + Postgres DB)",
        value: "render",
        description: "Generates render.yaml for one-click Infrastructure-as-Code deployment"
      },
      {
        name: "Railway (Containerized Service Deployment)",
        value: "railway",
        description: "Generates railway.json container configuration"
      },
      {
        name: "Vercel + Render (Static Angular UI on Vercel + NestJS API on Render)",
        value: "vercel-render",
        description: "Configures Vercel static build and Render backend environment"
      },
      {
        name: "Self-Hosted Production Docker (Docker Compose)",
        value: "docker",
        description: "Generates production docker-compose.prod.yml with Nginx reverse proxy"
      }
    ]
  });
  const spinner = (0, import_ora3.default)(`Generating deployment configuration files for ${platform}...`).start();
  try {
    if (platform === "render") {
      const renderYaml = `
services:
  - type: web
    name: webiu-server
    env: node
    buildCommand: cd webiu-server && npm install && npm run build
    startCommand: cd webiu-server && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: webiu-ui
    env: static
    buildCommand: cd webiu-ui && npm install && npm run build
    staticPublishPath: ./webiu-ui/dist/webiu-ui/browser
`.trim();
      await import_fs_extra2.default.writeFile(import_path3.default.join(process.cwd(), "render.yaml"), renderYaml);
      spinner.succeed(import_chalk4.default.green("Generated render.yaml successfully! XD"));
      console.log(`
${import_chalk4.default.bold.yellow("Next Steps for Render:")}`);
      console.log("  1. Commit and push your changes to GitHub.");
      console.log('  2. Go to https://dashboard.render.com and choose "New Blueprint Group".');
      console.log("  3. Select your GitHub repo to deploy automatically!\n");
    } else if (platform === "docker") {
      const dockerProd = `
version: '3.8'
services:
  webiu-server:
    build:
      context: ./webiu-server
    ports:
      - "3000:3000"
    restart: always

  webiu-ui:
    build:
      context: ./webiu-ui
    ports:
      - "80:80"
    restart: always
`.trim();
      await import_fs_extra2.default.writeFile(import_path3.default.join(process.cwd(), "docker-compose.prod.yml"), dockerProd);
      spinner.succeed(import_chalk4.default.green("Generated docker-compose.prod.yml successfully! :D"));
      console.log(`
${import_chalk4.default.bold.yellow("Next Steps for Docker:")}`);
      console.log(`  1. Run ${import_chalk4.default.cyan("docker compose -f docker-compose.prod.yml up -d")}`);
      console.log("  2. Access your portal at http://localhost\n");
    } else {
      spinner.succeed(import_chalk4.default.green(`Prepared deployment instructions for ${platform}!`));
    }
  } catch (err) {
    spinner.fail(import_chalk4.default.red("Failed to generate deployment templates."));
    console.error(err);
  }
}

// src-cli/commands/help.ts
var import_chalk5 = __toESM(require("chalk"));
async function helpCommand() {
  console.log(`
${import_chalk5.default.bold.cyan("====================================================================")}
${import_chalk5.default.bold.yellow("                        WEBIU CLI TOOL - HELP MANUAL                ")}
${import_chalk5.default.bold.cyan("====================================================================")}

${import_chalk5.default.bold("Usage:")} webiu [command] [options]

${import_chalk5.default.bold.green("Commands:")}
  ${import_chalk5.default.bold.cyan("init")}          Interactively initialize a new Webiu portal project
  ${import_chalk5.default.bold.cyan("dev")}           Start local development server (Frontend + Backend concurrently)
  ${import_chalk5.default.bold.cyan("build")}         Build production assets for both webiu-ui and webiu-server
  ${import_chalk5.default.bold.cyan("config")}        Re-configure Organization metadata, branding, or environment variables
  ${import_chalk5.default.bold.cyan("deploy")}        Launch interactive deployment generator for Render, Railway, Vercel, or Docker
  ${import_chalk5.default.bold.cyan("docker:up")}     Spin up containerized development environment using Docker Compose
  ${import_chalk5.default.bold.cyan("docker:down")}   Stop and remove running local Docker containers
  ${import_chalk5.default.bold.cyan("help")}          Display detailed command usage and architectural instructions

${import_chalk5.default.bold.green("Options:")}
  ${import_chalk5.default.bold.cyan("-v, --version")} Output the current version of webiu
  ${import_chalk5.default.bold.cyan("-h, --help")}    Display help information for command

${import_chalk5.default.bold.magenta("Examples:")}
  $ ${import_chalk5.default.cyan("npx webiu init")}
  $ ${import_chalk5.default.cyan("npx webiu dev")}
  $ ${import_chalk5.default.cyan("npx webiu deploy")}

${import_chalk5.default.gray("For detailed online documentation, visit:")} ${import_chalk5.default.underline.blue("https://github.com/c2siorg/Webiu")}
${import_chalk5.default.gray("Maintainers: C2SI Organization (Community Software Infrastructure)")} XD
`);
}

// src-cli/commands/docker.ts
var import_execa = require("execa");
var import_chalk6 = __toESM(require("chalk"));
async function dockerUpCommand() {
  console.log(`
${import_chalk6.default.bold.cyan("Starting Docker containerized environment... :D")}
`);
  try {
    await (0, import_execa.execa)("docker", ["compose", "up", "-d"], { stdio: "inherit" });
    console.log(import_chalk6.default.green("\nDocker containers started successfully! XD"));
  } catch (err) {
    console.error(import_chalk6.default.red("Failed to start Docker containers:"), err);
  }
}
async function dockerDownCommand() {
  console.log(`
${import_chalk6.default.bold.cyan("Stopping Docker containerized environment...")}
`);
  try {
    await (0, import_execa.execa)("docker", ["compose", "down"], { stdio: "inherit" });
    console.log(import_chalk6.default.green("\nDocker containers stopped cleanly."));
  } catch (err) {
    console.error(import_chalk6.default.red("Failed to stop Docker containers:"), err);
  }
}

// src-cli/index.ts
var program = new import_commander.Command();
program.name("webiu").description("CLI tool to generate, configure, and deploy Webiu community portals").version("1.0.0");
program.command("init").description("Interactively initialize a new Webiu portal project").option("-n, --name <name>", "Project name").action(initCommand);
program.command("dev").description("Start local development server (Frontend + Backend concurrently)").action(devCommand);
program.command("build").description("Build production assets for both webiu-ui and webiu-server").action(buildCommand);
program.command("config").description("Re-configure Organization metadata, branding, or environment variables").action(configCommand);
program.command("deploy").description("Launch interactive deployment generator for Render, Railway, Vercel, or Docker").action(deployCommand);
program.command("docker:up").description("Spin up containerized development environment using Docker Compose").action(dockerUpCommand);
program.command("docker:down").description("Stop and remove running local Docker containers").action(dockerDownCommand);
program.command("help").description("Display detailed command usage and architectural instructions").action(helpCommand);
program.parse(process.argv);
if (!process.argv.slice(2).length) {
  helpCommand();
}
