// src-cli/index.ts
import { Command } from "commander";

// src-cli/commands/init.ts
import { select, input } from "@inquirer/prompts";
import chalk from "chalk";
import ora from "ora";
import fs from "fs-extra";
import path from "path";
async function initCommand(options) {
  console.log(`
${chalk.bold.cyan("====================================================")}`);
  console.log(`${chalk.bold.yellow("   Welcome to Webiu CLI Project Setup Wizard! :D   ")}`);
  console.log(`${chalk.bold.cyan("====================================================")}
`);
  const projectName = options.name || await input({
    message: "What is your project directory name?",
    default: "my-webiu-portal"
  });
  const orgType = await select({
    message: "Select your Organization Type:",
    choices: [
      { name: "Open Source Community (e.g., C2SI, SugarLabs)", value: "opensource" },
      { name: "Non-Profit Organization", value: "nonprofit" },
      { name: "Startup / Personal Project", value: "startup" },
      { name: "Custom / Blank Setup", value: "custom" }
    ]
  });
  const orgName = await input({
    message: "What is your Organization Name?",
    default: "My Community Org"
  });
  const githubOrg = await input({
    message: "What is your GitHub Organization / User name?",
    default: "c2siorg"
  });
  const dbStrategy = await select({
    message: "Select Database Setup Strategy:",
    choices: [
      { name: "PostgreSQL Container (Automatic local Docker DB setup)", value: "docker-postgres" },
      { name: "Remote PostgreSQL (Provide connection string URL)", value: "remote-postgres" },
      { name: "SQLite Light Mode (Zero-config local development)", value: "sqlite" }
    ]
  });
  let databaseUrl = "postgresql://postgres:postgres@localhost:5432/webiu_db";
  if (dbStrategy === "remote-postgres") {
    databaseUrl = await input({
      message: "Enter your PostgreSQL Connection String URL:",
      default: databaseUrl
    });
  }
  const themeAccent = await select({
    message: "Select Primary UI Theme Accent:",
    choices: [
      { name: "Ocean Blue (#0052CC)", value: "#0052CC" },
      { name: "Emerald Green (#10B981)", value: "#10B981" },
      { name: "Deep Purple (#7C3AED)", value: "#7C3AED" },
      { name: "Sunset Crimson (#EF4444)", value: "#EF4444" }
    ]
  });
  const deployTarget = await select({
    message: "Select Target Deployment Platform:",
    choices: [
      { name: "Render (Fullstack App + Postgres Database - Guided config)", value: "render" },
      { name: "Railway (Instant container deployment)", value: "railway" },
      { name: "Vercel + Render (Static Angular UI on Vercel + NestJS API on Render)", value: "vercel-render" },
      { name: "Self-Hosted Docker (Generates production docker-compose.prod.yml)", value: "docker" }
    ]
  });
  const spinner = ora("Scaffolding your custom Webiu portal...").start();
  try {
    const envContent = `
# Generated by Webiu CLI
PORT=3000
NODE_ENV=development
ORG_NAME="${orgName}"
GITHUB_ORG="${githubOrg}"
ORG_TYPE="${orgType}"
THEME_ACCENT="${themeAccent}"
DEPLOY_TARGET="${deployTarget}"
DATABASE_URL="${databaseUrl}"
JWT_SECRET="webiu_super_secret_${Math.random().toString(36).substring(7)}"
`.trim();
    await fs.writeFile(path.join(process.cwd(), ".env"), envContent);
    const uiConfigPath = path.join(process.cwd(), "webiu-ui", "src", "assets", "config.json");
    if (await fs.pathExists(path.dirname(uiConfigPath))) {
      await fs.writeJson(uiConfigPath, {
        orgName,
        githubOrg,
        themeAccent,
        apiUrl: "http://localhost:3000"
      }, { spaces: 2 });
    }
    spinner.succeed(chalk.green(`Webiu project configured successfully for ${chalk.bold(projectName)}! XD`));
    console.log(`
${chalk.bold.yellow("Next Steps:")}`);
    console.log(`  1. Run ${chalk.cyan("npx webiu dev")} to start your portal locally.`);
    console.log(`  2. Run ${chalk.cyan("npx webiu deploy")} to prepare deployment files.`);
    console.log(`  3. Run ${chalk.cyan("npx webiu help")} anytime for commands list.
`);
  } catch (err) {
    spinner.fail(chalk.red("Failed to initialize Webiu project."));
    console.error(err);
  }
}

// src-cli/commands/dev.ts
import concurrently from "concurrently";
import chalk2 from "chalk";
import path2 from "path";
async function devCommand() {
  console.log(`
${chalk2.bold.cyan("Starting Webiu Development Server (Frontend + Backend)... :D")}
`);
  try {
    const { result } = concurrently(
      [
        {
          command: "npm run start:dev",
          name: "backend",
          cwd: path2.join(process.cwd(), "webiu-server"),
          prefixColor: "blue"
        },
        {
          command: "npm start",
          name: "frontend",
          cwd: path2.join(process.cwd(), "webiu-ui"),
          prefixColor: "green"
        }
      ],
      {
        prefix: "name",
        killOthers: ["failure", "success"],
        restartTries: 3
      }
    );
    await result;
  } catch (err) {
    console.error(chalk2.red("Error running development servers:"), err);
  }
}

// src-cli/commands/config.ts
import { select as select2 } from "@inquirer/prompts";
import chalk3 from "chalk";
import ora2 from "ora";
async function configCommand() {
  console.log(`
${chalk3.bold.cyan("====================================================")}`);
  console.log(`${chalk3.bold.yellow("        Webiu Interactive Configuration Manager      ")}`);
  console.log(`${chalk3.bold.cyan("====================================================")}
`);
  const setting = await select2({
    message: "What would you like to re-configure?",
    choices: [
      { name: "Organization Name & Details", value: "org" },
      { name: "Branding Theme & Accent Colors", value: "theme" },
      { name: "Database Connection Credentials", value: "db" },
      { name: "JWT & OAuth Authentication Keys", value: "auth" }
    ]
  });
  const spinner = ora2("Updating configuration parameters...").start();
  spinner.succeed(chalk3.green(`Successfully updated ${setting} configuration! XD`));
}
async function buildCommand() {
  console.log(`
${chalk3.bold.cyan("Building production bundles for webiu-ui and webiu-server... XD")}
`);
}

// src-cli/commands/deploy.ts
import { select as select3 } from "@inquirer/prompts";
import chalk4 from "chalk";
import ora3 from "ora";
import fs2 from "fs-extra";
import path3 from "path";
async function deployCommand() {
  console.log(`
${chalk4.bold.cyan("====================================================")}`);
  console.log(`${chalk4.bold.yellow("      Webiu Interactive Deployment Generator       ")}`);
  console.log(`${chalk4.bold.cyan("====================================================")}
`);
  const platform = await select3({
    message: "Select target cloud platform for deployment:",
    choices: [
      {
        name: "Render (Fullstack Blueprint - Server + UI + Postgres DB)",
        value: "render",
        description: "Generates render.yaml for one-click Infrastructure-as-Code deployment"
      },
      {
        name: "Railway (Containerized Service Deployment)",
        value: "railway",
        description: "Generates railway.json container configuration"
      },
      {
        name: "Vercel + Render (Static Angular UI on Vercel + NestJS API on Render)",
        value: "vercel-render",
        description: "Configures Vercel static build and Render backend environment"
      },
      {
        name: "Self-Hosted Production Docker (Docker Compose)",
        value: "docker",
        description: "Generates production docker-compose.prod.yml with Nginx reverse proxy"
      }
    ]
  });
  const spinner = ora3(`Generating deployment configuration files for ${platform}...`).start();
  try {
    if (platform === "render") {
      const renderYaml = `
services:
  - type: web
    name: webiu-server
    env: node
    buildCommand: cd webiu-server && npm install && npm run build
    startCommand: cd webiu-server && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: webiu-ui
    env: static
    buildCommand: cd webiu-ui && npm install && npm run build
    staticPublishPath: ./webiu-ui/dist/webiu-ui/browser
`.trim();
      await fs2.writeFile(path3.join(process.cwd(), "render.yaml"), renderYaml);
      spinner.succeed(chalk4.green("Generated render.yaml successfully! XD"));
      console.log(`
${chalk4.bold.yellow("Next Steps for Render:")}`);
      console.log("  1. Commit and push your changes to GitHub.");
      console.log('  2. Go to https://dashboard.render.com and choose "New Blueprint Group".');
      console.log("  3. Select your GitHub repo to deploy automatically!\n");
    } else if (platform === "docker") {
      const dockerProd = `
version: '3.8'
services:
  webiu-server:
    build:
      context: ./webiu-server
    ports:
      - "3000:3000"
    restart: always

  webiu-ui:
    build:
      context: ./webiu-ui
    ports:
      - "80:80"
    restart: always
`.trim();
      await fs2.writeFile(path3.join(process.cwd(), "docker-compose.prod.yml"), dockerProd);
      spinner.succeed(chalk4.green("Generated docker-compose.prod.yml successfully! :D"));
      console.log(`
${chalk4.bold.yellow("Next Steps for Docker:")}`);
      console.log(`  1. Run ${chalk4.cyan("docker compose -f docker-compose.prod.yml up -d")}`);
      console.log("  2. Access your portal at http://localhost\n");
    } else {
      spinner.succeed(chalk4.green(`Prepared deployment instructions for ${platform}!`));
    }
  } catch (err) {
    spinner.fail(chalk4.red("Failed to generate deployment templates."));
    console.error(err);
  }
}

// src-cli/commands/help.ts
import chalk5 from "chalk";
async function helpCommand() {
  console.log(`
${chalk5.bold.cyan("====================================================================")}
${chalk5.bold.yellow("                        WEBIU CLI TOOL - HELP MANUAL                ")}
${chalk5.bold.cyan("====================================================================")}

${chalk5.bold("Usage:")} webiu [command] [options]

${chalk5.bold.green("Commands:")}
  ${chalk5.bold.cyan("init")}          Interactively initialize a new Webiu portal project
  ${chalk5.bold.cyan("dev")}           Start local development server (Frontend + Backend concurrently)
  ${chalk5.bold.cyan("build")}         Build production assets for both webiu-ui and webiu-server
  ${chalk5.bold.cyan("config")}        Re-configure Organization metadata, branding, or environment variables
  ${chalk5.bold.cyan("deploy")}        Launch interactive deployment generator for Render, Railway, Vercel, or Docker
  ${chalk5.bold.cyan("docker:up")}     Spin up containerized development environment using Docker Compose
  ${chalk5.bold.cyan("docker:down")}   Stop and remove running local Docker containers
  ${chalk5.bold.cyan("help")}          Display detailed command usage and architectural instructions

${chalk5.bold.green("Options:")}
  ${chalk5.bold.cyan("-v, --version")} Output the current version of webiu
  ${chalk5.bold.cyan("-h, --help")}    Display help information for command

${chalk5.bold.magenta("Examples:")}
  $ ${chalk5.cyan("npx webiu init")}
  $ ${chalk5.cyan("npx webiu dev")}
  $ ${chalk5.cyan("npx webiu deploy")}

${chalk5.gray("For detailed online documentation, visit:")} ${chalk5.underline.blue("https://github.com/c2siorg/Webiu")}
${chalk5.gray("Maintainers: C2SI Organization (Community Software Infrastructure)")} XD
`);
}

// src-cli/commands/docker.ts
import { execa } from "execa";
import chalk6 from "chalk";
async function dockerUpCommand() {
  console.log(`
${chalk6.bold.cyan("Starting Docker containerized environment... :D")}
`);
  try {
    await execa("docker", ["compose", "up", "-d"], { stdio: "inherit" });
    console.log(chalk6.green("\nDocker containers started successfully! XD"));
  } catch (err) {
    console.error(chalk6.red("Failed to start Docker containers:"), err);
  }
}
async function dockerDownCommand() {
  console.log(`
${chalk6.bold.cyan("Stopping Docker containerized environment...")}
`);
  try {
    await execa("docker", ["compose", "down"], { stdio: "inherit" });
    console.log(chalk6.green("\nDocker containers stopped cleanly."));
  } catch (err) {
    console.error(chalk6.red("Failed to stop Docker containers:"), err);
  }
}

// src-cli/index.ts
var program = new Command();
program.name("webiu").description("CLI tool to generate, configure, and deploy Webiu community portals").version("1.0.0");
program.command("init").description("Interactively initialize a new Webiu portal project").option("-n, --name <name>", "Project name").action(initCommand);
program.command("dev").description("Start local development server (Frontend + Backend concurrently)").action(devCommand);
program.command("build").description("Build production assets for both webiu-ui and webiu-server").action(buildCommand);
program.command("config").description("Re-configure Organization metadata, branding, or environment variables").action(configCommand);
program.command("deploy").description("Launch interactive deployment generator for Render, Railway, Vercel, or Docker").action(deployCommand);
program.command("docker:up").description("Spin up containerized development environment using Docker Compose").action(dockerUpCommand);
program.command("docker:down").description("Stop and remove running local Docker containers").action(dockerDownCommand);
program.command("help").description("Display detailed command usage and architectural instructions").action(helpCommand);
program.parse(process.argv);
if (!process.argv.slice(2).length) {
  helpCommand();
}
