import { select, input } from '@inquirer/prompts';
import chalk from 'chalk';
import ora from 'ora';
import fs from 'fs-extra';
import path from 'path';

export async function initCommand(options: { name?: string }) {
  console.log(`\n${chalk.bold.cyan('====================================================')}`);
  console.log(`${chalk.bold.yellow('   Welcome to Webiu CLI Project Setup Wizard! :D   ')}`);
  console.log(`${chalk.bold.cyan('====================================================')}\n`);

  const projectName = options.name || await input({
    message: 'What is your project directory name?',
    default: 'my-webiu-portal',
  });

  const orgType = await select({
    message: 'Select your Organization Type:',
    choices: [
      { name: 'Open Source Community (e.g., C2SI, SugarLabs)', value: 'opensource' },
      { name: 'Non-Profit Organization', value: 'nonprofit' },
      { name: 'Startup / Personal Project', value: 'startup' },
      { name: 'Custom / Blank Setup', value: 'custom' },
    ],
  });

  const orgName = await input({
    message: 'What is your Organization Name?',
    default: 'My Community Org',
  });

  const githubOrg = await input({
    message: 'What is your GitHub Organization / User name?',
    default: 'c2siorg',
  });

  const dbStrategy = await select({
    message: 'Select Database Setup Strategy:',
    choices: [
      { name: 'PostgreSQL Container (Automatic local Docker DB setup)', value: 'docker-postgres' },
      { name: 'Remote PostgreSQL (Provide connection string URL)', value: 'remote-postgres' },
      { name: 'SQLite Light Mode (Zero-config local development)', value: 'sqlite' },
    ],
  });

  let databaseUrl = 'postgresql://postgres:postgres@localhost:5432/webiu_db';
  if (dbStrategy === 'remote-postgres') {
    databaseUrl = await input({
      message: 'Enter your PostgreSQL Connection String URL:',
      default: databaseUrl,
    });
  }

  const themeAccent = await select({
    message: 'Select Primary UI Theme Accent:',
    choices: [
      { name: 'Ocean Blue (#0052CC)', value: '#0052CC' },
      { name: 'Emerald Green (#10B981)', value: '#10B981' },
      { name: 'Deep Purple (#7C3AED)', value: '#7C3AED' },
      { name: 'Sunset Crimson (#EF4444)', value: '#EF4444' },
    ],
  });

  const deployTarget = await select({
    message: 'Select Target Deployment Platform:',
    choices: [
      { name: 'Render (Fullstack App + Postgres Database - Guided config)', value: 'render' },
      { name: 'Railway (Instant container deployment)', value: 'railway' },
      { name: 'Vercel + Render (Static Angular UI on Vercel + NestJS API on Render)', value: 'vercel-render' },
      { name: 'Self-Hosted Docker (Generates production docker-compose.prod.yml)', value: 'docker' },
    ],
  });

  const spinner = ora('Scaffolding your custom Webiu portal...').start();

  try {
    // Generate .env content
    const envContent = `
# Generated by Webiu CLI
PORT=3000
NODE_ENV=development
ORG_NAME="${orgName}"
GITHUB_ORG="${githubOrg}"
ORG_TYPE="${orgType}"
THEME_ACCENT="${themeAccent}"
DEPLOY_TARGET="${deployTarget}"
DATABASE_URL="${databaseUrl}"
JWT_SECRET="webiu_super_secret_${Math.random().toString(36).substring(7)}"
`.trim();

    await fs.writeFile(path.join(process.cwd(), '.env'), envContent);

    // Write webiu-ui config
    const uiConfigPath = path.join(process.cwd(), 'webiu-ui', 'src', 'assets', 'config.json');
    if (await fs.pathExists(path.dirname(uiConfigPath))) {
      await fs.writeJson(uiConfigPath, {
        orgName,
        githubOrg,
        themeAccent,
        apiUrl: 'http://localhost:3000',
      }, { spaces: 2 });
    }

    spinner.succeed(chalk.green(`Webiu project configured successfully for ${chalk.bold(projectName)}! XD`));

    console.log(`\n${chalk.bold.yellow('Next Steps:')}`);
    console.log(`  1. Run ${chalk.cyan('npx webiu dev')} to start your portal locally.`);
    console.log(`  2. Run ${chalk.cyan('npx webiu deploy')} to prepare deployment files.`);
    console.log(`  3. Run ${chalk.cyan('npx webiu help')} anytime for commands list.\n`);
  } catch (err: any) {
    spinner.fail(chalk.red('Failed to initialize Webiu project.'));
    console.error(err);
  }
}
